### ISSUE TITLE
MainActivity.class update

### ISSUE THREAD

**Issue by mledwards** [openforge/capacitor-game-connect#23]
Incase this is helpful, where the instructions say to update the `MainActivity.class`, it means the MainActivity class in the `MainActivity.java` file, it should look something like this...

```
package [YOUR_APP_ID_SHOULD_ALREADY_BE_HERE];

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.openforge.capacitorgameconnect.CapacitorGameConnectPlugin;

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        registerPlugin(CapacitorGameConnectPlugin.class);
        super.onCreate(savedInstanceState);
    }
}
```

**Comment by Ricardo385** [comment]
Hey @mledwards thanks for this recommendation! Since this is not an issue, I'm going to close it, I have already created a ticket in our internal to update our documentation to be more clear in this part.

Best regards,
