### ISSUE TITLE
Capacitor 5.0 Support

### ISSUE THREAD

**Issue by wainwrightmark** [openforge/capacitor-game-connect#7]
Are you planning to release a version supporting Capacitor 5.0?

I've been using the automatic migration (https://capacitorjs.com/docs/updating/plugins/5-0) and installing it from a local path. This is working for me but it would be nice to have an updated version available on npm.

**Comment by briannastatic** [comment]
Eagerly waiting for 5.0 support as well.

**Comment by Ricardo385** [comment]
Hey @briannastatic @wainwrightmark thanks a lot for open this conversation! We are planning to get this Capacitor 5 support very soon, we are going to reach this conversation again when the feature is implemented.

Regards

**Comment by Frozo13** [comment]
Hi, is there an estimated release date?

**Comment by Ricardo385** [comment]
Hey @Frozo13 [v5.0.0](https://github.com/openforge/capacitor-game-connect/tree/v5.0.0) is up now! 
Please check the notes for the version to see what's new. Thank you for using the plugin!
